"""
Rewrite ORM model.
"""
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Text, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base_class import Base

if TYPE_CHECKING:
    from app.models.analysis import Analysis


class Rewrite(Base):
    """Stores AI-generated resume rewrites linked to an analysis."""

    __tablename__ = "rewrites"

    # ── Primary Key ───────────────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        index=True,
    )

    # ── Foreign Keys ──────────────────────────────────────────────────────────
    analysis_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("analyses.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Content ───────────────────────────────────────────────────────────────
    rewritten_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Full rewritten resume text generated by AI",
    )

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    analysis: Mapped["Analysis"] = relationship(
        "Analysis",
        back_populates="rewrites",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<Rewrite id={self.id} analysis_id={self.analysis_id}>"
