"""Create initial application schema

Revision ID: 20260712_0001
Revises: 
Create Date: 2026-07-12 00:00:00.000000
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20260712_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)

    op.create_table(
        "resumes",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("storage_url", sa.String(length=2048), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True, comment="File size in bytes"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_resumes_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
    )
    op.create_index(op.f("ix_resumes_id"), "resumes", ["id"], unique=False)
    op.create_index(op.f("ix_resumes_user_id"), "resumes", ["user_id"], unique=False)

    op.create_table(
        "analyses",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("resume_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_description", sa.Text(), nullable=False),
        sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Full structured AI analysis output"),
        sa.Column("ats_score", sa.Integer(), nullable=True, comment="ATS score 0-100"),
        sa.Column("resume_score", sa.Integer(), nullable=True, comment="Overall resume quality score 0-100"),
        sa.Column("skill_match_percentage", sa.Float(), nullable=True, comment="Percentage of JD skills matched"),
        sa.Column("status", sa.String(length=50), server_default=sa.text("'pending'"), nullable=False, comment="One of: pending, processing, completed, failed"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], name=op.f("fk_analyses_resume_id_resumes"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_analyses_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
    )
    op.create_index(op.f("ix_analyses_id"), "analyses", ["id"], unique=False)
    op.create_index(op.f("ix_analyses_resume_id"), "analyses", ["resume_id"], unique=False)
    op.create_index(op.f("ix_analyses_user_id"), "analyses", ["user_id"], unique=False)

    op.create_table(
        "rewrites",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("analysis_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("rewritten_text", sa.Text(), nullable=False, comment="Full rewritten resume text generated by AI"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], name=op.f("fk_rewrites_analysis_id_analyses"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rewrites")),
    )
    op.create_index(op.f("ix_rewrites_analysis_id"), "rewrites", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_rewrites_id"), "rewrites", ["id"], unique=False)

    op.create_table(
        "resume_embeddings",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("resume_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("chunk_type", sa.String(length=50), nullable=False, comment="skills, experience, education, summary"),
        sa.Column("embedding", Vector(384), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], name=op.f("fk_resume_embeddings_resume_id_resumes"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_resume_embeddings_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume_embeddings")),
    )
    op.create_index(op.f("ix_resume_embeddings_id"), "resume_embeddings", ["id"], unique=False)
    op.create_index(op.f("ix_resume_embeddings_resume_id"), "resume_embeddings", ["resume_id"], unique=False)
    op.create_index(op.f("ix_resume_embeddings_user_id"), "resume_embeddings", ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_resume_embeddings_user_id"), table_name="resume_embeddings")
    op.drop_index(op.f("ix_resume_embeddings_resume_id"), table_name="resume_embeddings")
    op.drop_index(op.f("ix_resume_embeddings_id"), table_name="resume_embeddings")
    op.drop_table("resume_embeddings")

    op.drop_index(op.f("ix_rewrites_id"), table_name="rewrites")
    op.drop_index(op.f("ix_rewrites_analysis_id"), table_name="rewrites")
    op.drop_table("rewrites")

    op.drop_index(op.f("ix_analyses_user_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_resume_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_id"), table_name="analyses")
    op.drop_table("analyses")

    op.drop_index(op.f("ix_resumes_user_id"), table_name="resumes")
    op.drop_index(op.f("ix_resumes_id"), table_name="resumes")
    op.drop_table("resumes")

    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
